---
# Update packages and install essentials (run as root)
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  become: true

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: dist
  become: true

- name: Install common packages
  ansible.builtin.apt:
    name: 
      - build-essential
      - curl
      - git
      - vim
      - unzip
      - htop
      - tmux
      - software-properties-common
      - openssh-server
      - radeontop
    state: present
  become: true


# Configure Git (for the non-root user)
- name: Ensure git is configured (user)
  ansible.builtin.git_config:
    name: user.name
    value: "Rainerino"
    scope: global
  become: false

- name: Set git email (user)
  ansible.builtin.git_config:
    name: user.email
    value: "albertyanyy@gmail.com"
    scope: global
  become: false

# Only modify system /etc/hosts via root if needed
- name: Check connectivity to raw.githubusercontent.com
  ansible.builtin.command:
    cmd: ping -c1 -W2 raw.githubusercontent.com
  register: ping_result
  changed_when: false
  ignore_errors: true
  become: false

- name: Add hosts entry if raw.githubusercontent.com is unreachable
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: '^185\.199\.108\.133\s+raw\.githubusercontent\.com'
    line: '185.199.108.133 raw.githubusercontent.com'
    state: present
    backup: yes
  become: true
  when: ping_result is failed


- name: Ensure fontconfig is installed
  apt:
    name: fontconfig
    state: present
    update_cache: yes
  become: true

- name: Copy Meslo Nerd Fonts from role files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/usr/local/share/fonts/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - "../fonts/MesloLGS NF Regular.ttf"
    - "../fonts/MesloLGS NF Bold.ttf"
    - "../fonts/MesloLGS NF Italic.ttf"
    - "../fonts/MesloLGS NF Bold Italic.ttf"
  register: meslo_download
  become: true

- name: Set correct ownership on font files
  file:
    path: "/usr/local/share/fonts/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ meslo_download.results | map(attribute='dest') | map('basename') | list }}"
  become: true

- name: Refresh system font cache
  ansible.builtin.command:
    cmd: fc-cache -fv
  become: true
